### ISSUE TITLE
test -e && rm -f

### ISSUE THREAD

**Issue by fbt** [jcnelson/vdev#67]
https://github.com/jcnelson/vdev/commit/e930843574a1b21e4dbe72fbe3e7bc4ea5432898
https://github.com/jcnelson/vdev/commit/4dda405e8b36f2a297a863572146af091c0eb37c
https://github.com/jcnelson/vdev/commit/f609bf1ab65958054cb038a54859b5b79bef71c9

These three commits break installing vdev into an empty dir with DESTDIR. It fails on the test and doesn't go further.
It's a useless test anyway btw. rm -f won't fail if the file doesn't exist.

**Comment by jcnelson** [comment]
Hi @fbt,

Sorry about that--it should have been `rm -f`.

I added those commands to stop the Makefile from trying to overwrite a binary while it's running (which will fail), or trying to overwrite a library while its in use (which will crash any process linked to it).

It should be fixed in ee6ee3dc516efa02a216246057d6685bf09b2580.

Thanks!

**Comment by fbt** [comment]
Yep, builds now.
